export const ALL_MEDICATIONS = [
  // Antipyretics
  { name: 'Cetal drops', type: 'liquid', mg_per_kg: 15, doses_per_day: 4, duration_days: 3, concentration_mg_per_ml: 100, notes: 'Paracetamol. 2-3 drops / kg per dose every 4-6 hours', category: 'Antipyretics' },
  { name: 'Pyral syp. (120)', type: 'liquid', mg_per_kg: 15, doses_per_day: 4, duration_days: 3, concentration_mg_per_ml: 24, notes: 'Paracetamol. 10-15 mg/kg per dose', category: 'Antipyretics' },
  { name: 'Abimol syp. (150)', type: 'liquid', mg_per_kg: 15, doses_per_day: 4, duration_days: 3, concentration_mg_per_ml: 30, notes: 'Paracetamol. 10-15 mg/kg per dose', category: 'Antipyretics' },
  { name: 'Fevano syp. (200)', type: 'liquid', mg_per_kg: 15, doses_per_day: 4, duration_days: 3, concentration_mg_per_ml: 40, notes: 'Paracetamol. 10-15 mg/kg per dose', category: 'Antipyretics' },
  { name: 'Paracetamol supp.', type: 'pill', mg_per_kg: 15, doses_per_day: 4, duration_days: 2, concentration_mg_per_ml: 0, notes: '10-15 mg/kg per dose', category: 'Antipyretics' },
  { name: 'Brufen syp.', type: 'liquid', mg_per_kg: 10, doses_per_day: 3, duration_days: 3, concentration_mg_per_ml: 20, notes: 'Ibuprofen. 5-10 mg/kg per dose every 6-8 hours', category: 'Antipyretics' },
  { name: 'Prof syp.', type: 'liquid', mg_per_kg: 10, doses_per_day: 3, duration_days: 3, concentration_mg_per_ml: 20, notes: 'Ibuprofen. 5-10 mg/kg per dose', category: 'Antipyretics' },
  { name: 'Ibuprofen supp.', type: 'pill', mg_per_kg: 10, doses_per_day: 3, duration_days: 3, concentration_mg_per_ml: 0, notes: '5-10 mg/kg per dose', category: 'Antipyretics' },
  { name: 'Ketofan drops', type: 'liquid', mg_per_kg: 1, doses_per_day: 3, duration_days: 3, concentration_mg_per_ml: 4, notes: 'Ketoprofen. 1 mg/kg per dose every 6-8 hours', category: 'Antipyretics' },
  { name: 'Ketofan syp.', type: 'liquid', mg_per_kg: 1, doses_per_day: 3, duration_days: 3, concentration_mg_per_ml: 4, notes: 'Ketoprofen. 1 mg/kg per dose', category: 'Antipyretics' },
  { name: 'Ketolac amp.', type: 'liquid', mg_per_kg: 0.5, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 30, notes: 'Ketorolac. 0.5 mg/kg per dose', category: 'Antipyretics' },

  // Antibiotics
  { name: 'Augmentin ES', type: 'liquid', mg_per_kg: 90, doses_per_day: 2, duration_days: 7, concentration_mg_per_ml: 120, notes: 'Co-Amoxiclav. 90 mg/kg/day divided every 12 hours', category: 'Antibiotics' },
  { name: 'Megamox', type: 'liquid', mg_per_kg: 90, doses_per_day: 2, duration_days: 7, concentration_mg_per_ml: 91.4, notes: 'Co-Amoxiclav. 80-90 mg/kg/day', category: 'Antibiotics' },
  { name: 'Curam', type: 'liquid', mg_per_kg: 90, doses_per_day: 2, duration_days: 7, concentration_mg_per_ml: 91.4, notes: 'Co-Amoxiclav. 80-90 mg/kg/day', category: 'Antibiotics' },
  { name: 'Amoxil', type: 'liquid', mg_per_kg: 90, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 50, notes: 'Amoxicillin. 40-90 mg/kg/day', category: 'Antibiotics' },
  { name: 'Unasyn', type: 'liquid', mg_per_kg: 150, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 50, notes: 'Ampicillin/Sulbactam. 150 mg/kg/day', category: 'Antibiotics' },
  { name: 'Cefotax', type: 'liquid', mg_per_kg: 150, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 100, notes: 'Cefotaxime. 100-150 mg/kg/day', category: 'Antibiotics' },
  { name: 'Ceftriaxone', type: 'liquid', mg_per_kg: 100, doses_per_day: 1, duration_days: 5, concentration_mg_per_ml: 100, notes: '50-100 mg/kg/day', category: 'Antibiotics' },
  { name: 'Cedax', type: 'liquid', mg_per_kg: 9, doses_per_day: 1, duration_days: 5, concentration_mg_per_ml: 36, notes: '9 mg/kg/day', category: 'Antibiotics' },
  { name: 'Zithromax', type: 'liquid', mg_per_kg: 10, doses_per_day: 1, duration_days: 3, concentration_mg_per_ml: 40, notes: 'Azithromycin. 10 mg/kg day 1, then 5 mg/kg', category: 'Antibiotics' },
  { name: 'Klacid', type: 'liquid', mg_per_kg: 15, doses_per_day: 2, duration_days: 7, concentration_mg_per_ml: 25, notes: 'Clarithromycin. 15 mg/kg/day', category: 'Antibiotics' },
  { name: 'Flagyl', type: 'liquid', mg_per_kg: 30, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 25, notes: 'Metronidazole. 30 mg/kg/day', category: 'Antibiotics' },
  { name: 'Dalacin C', type: 'liquid', mg_per_kg: 40, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 15, notes: 'Clindamycin. 20-40 mg/kg/day', category: 'Antibiotics' },
  { name: 'Vancomycin', type: 'liquid', mg_per_kg: 60, doses_per_day: 4, duration_days: 7, concentration_mg_per_ml: 50, notes: '40-60 mg/kg/day', category: 'Antibiotics' },
  { name: 'Meronem', type: 'liquid', mg_per_kg: 60, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 100, notes: 'Meropenem. 60 mg/kg/day', category: 'Antibiotics' },
  { name: 'Tavanic', type: 'pill', mg_per_kg: 20, doses_per_day: 1, duration_days: 5, concentration_mg_per_ml: 0, notes: 'Levofloxacin. 10-20 mg/kg/day', category: 'Antibiotics' },

  // Cough
  { name: 'Mucosol', type: 'liquid', mg_per_kg: 0.5, doses_per_day: 3, duration_days: 5, concentration_mg_per_ml: 4.8, notes: '0.5 ml / kg / day', category: 'Cough' },
  { name: 'Bronchicum', type: 'liquid', mg_per_kg: 0, doses_per_day: 3, duration_days: 5, concentration_mg_per_ml: 0, notes: 'According to age', category: 'Cough' },
  { name: 'Ivypront', type: 'liquid', mg_per_kg: 0, doses_per_day: 3, duration_days: 5, concentration_mg_per_ml: 0, notes: 'According to age', category: 'Cough' },
  { name: 'Tussistop', type: 'liquid', mg_per_kg: 0, doses_per_day: 3, duration_days: 5, concentration_mg_per_ml: 0, notes: 'According to age', category: 'Cough' },
  { name: 'Oplex', type: 'liquid', mg_per_kg: 0, doses_per_day: 3, duration_days: 5, concentration_mg_per_ml: 0, notes: 'According to age', category: 'Cough' },

  // From PDF Screenshots
  { name: 'Acetylcistein', type: 'liquid', mg_per_kg: 100, doses_per_day: 3, duration_days: 5, concentration_mg_per_ml: 50, notes: 'Mucolytic. 200-400 mg PO up to 3x daily. Paracetamol tox: LD 140mg/kg, MD 70mg/kg q4h', category: 'Mucolytics' },
  { name: 'Acyclovir', type: 'liquid', mg_per_kg: 20, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 40, notes: 'HSV: 20 mg/kg/8h IVI. Chickenpox: 10-20 mg/kg/8h IVI.', category: 'Antiviral' },
  { name: 'Adenocor', type: 'liquid', mg_per_kg: 0.15, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 3, notes: 'Adenosine. SVT: 150 mcg/kg IV (0.15 mg/kg) rapid push.', category: 'Cardiac' },
  { name: 'Amikin', type: 'liquid', mg_per_kg: 15, doses_per_day: 1, duration_days: 7, concentration_mg_per_ml: 250, notes: 'Amikacin. 15-18 mg/kg q24-48h based on PMA.', category: 'Antibiotics' },
  { name: 'Amiodarone', type: 'liquid', mg_per_kg: 15, doses_per_day: 1, duration_days: 7, concentration_mg_per_ml: 50, notes: 'LD 5 mg/kg IVI over 30-60 min. MD 7-15 mcg/kg/min.', category: 'Cardiac' },
  { name: 'Human Albumin 20%', type: 'liquid', mg_per_kg: 1000, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 200, notes: '0.5-1 g/kg/dose (500-1000 mg/kg).', category: 'Miscellaneous' },
  { name: 'Atrovent', type: 'liquid', mg_per_kg: 0.1, doses_per_day: 3, duration_days: 5, concentration_mg_per_ml: 0.25, notes: 'Ipratropium. 75-175 mcg via nebulizer.', category: 'Asthma' },
  { name: 'Averozolid', type: 'liquid', mg_per_kg: 30, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 20, notes: 'Linezolid. 10 mg/kg/dose q8-12h.', category: 'Antibiotics' },
  { name: 'Bebe-vit', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 30, concentration_mg_per_ml: 0, notes: 'Multivitamin drops. 1 ml daily.', category: 'Vitamins' },
  { name: 'Sodium Benzoate', type: 'liquid', mg_per_kg: 250, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 100, notes: '250 mg/kg loading, then up to 250 mg/kg/day.', category: 'Emergency' },
  { name: 'Sodium Bicarbonate 8.4%', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 1, notes: '1-2 mEq/kg (1 mEq = 1 ml).', category: 'Emergency' },
  { name: 'Biotin Forte', type: 'pill', mg_per_kg: 0, doses_per_day: 1, duration_days: 30, concentration_mg_per_ml: 0, notes: '5-10 mg once daily.', category: 'Vitamins' },
  { name: 'Caffeinospire', type: 'liquid', mg_per_kg: 20, doses_per_day: 1, duration_days: 7, concentration_mg_per_ml: 20, notes: 'Caffeine Citrate. LD 20-25 mg/kg, MD 5-10 mg/kg/day.', category: 'Emergency' },
  { name: 'Calcium Chloride 10%', type: 'liquid', mg_per_kg: 70, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 100, notes: '35-70 mg/kg (0.35-0.7 ml/kg).', category: 'Emergency' },
  { name: 'Calcium Gluconate 10%', type: 'liquid', mg_per_kg: 200, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 100, notes: '1-2 ml/kg (100-200 mg/kg).', category: 'Emergency' },
  { name: 'Capoten', type: 'pill', mg_per_kg: 0.1, doses_per_day: 3, duration_days: 30, concentration_mg_per_ml: 0, notes: 'Captopril. 0.01 - 0.05 mg/kg/dose q8-12h.', category: 'Cardiac' },
  { name: 'Ceclor', type: 'liquid', mg_per_kg: 20, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 25, notes: 'Cefaclor. 20 mg/kg/day divided q8h.', category: 'Antibiotics' },
  { name: 'Cefazolin', type: 'liquid', mg_per_kg: 75, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 100, notes: '25 mg/kg/dose q8-12h.', category: 'Antibiotics' },
  { name: 'Cefdin', type: 'liquid', mg_per_kg: 14, doses_per_day: 1, duration_days: 7, concentration_mg_per_ml: 25, notes: 'Cefdinir. 14 mg/kg/day once daily.', category: 'Antibiotics' },
  { name: 'Chloral Hydrate', type: 'liquid', mg_per_kg: 50, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 100, notes: '25-50 mg/kg PO.', category: 'Sedatives' },
  { name: 'Cidamex', type: 'pill', mg_per_kg: 5, doses_per_day: 1, duration_days: 30, concentration_mg_per_ml: 0, notes: 'Acetazolamide. 5 mg/kg/dose q24h.', category: 'Cardiac' },
  { name: 'Ciprofloxacin', type: 'liquid', mg_per_kg: 20, doses_per_day: 2, duration_days: 7, concentration_mg_per_ml: 2, notes: '6-10 mg/kg/dose q12h IVI.', category: 'Antibiotics' },
  { name: 'Claforan', type: 'liquid', mg_per_kg: 150, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 100, notes: 'Cefotaxime. 50 mg/kg/dose q8-12h.', category: 'Antibiotics' },
  { name: 'Clexane', type: 'liquid', mg_per_kg: 4, doses_per_day: 2, duration_days: 7, concentration_mg_per_ml: 100, notes: 'Enoxaparin. 1.7-2 mg/kg/dose q12h SubQ.', category: 'Miscellaneous' },
  { name: 'Colimex', type: 'liquid', mg_per_kg: 150000, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 50000, notes: 'Colistin. 150,000 units/kg/day PO.', category: 'Antibiotics' },
  { name: 'Curosurf', type: 'liquid', mg_per_kg: 200, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 80, notes: 'Poractant alfa. 100-200 mg/kg (1.25-2.5 ml/kg).', category: 'Miscellaneous' },
  { name: 'Cymevene', type: 'liquid', mg_per_kg: 12, doses_per_day: 2, duration_days: 42, concentration_mg_per_ml: 50, notes: 'Ganciclovir. 6 mg/kg/dose q12h for 6 weeks.', category: 'Antiviral' },
  { name: 'Dexamethasone', type: 'liquid', mg_per_kg: 0.2, doses_per_day: 2, duration_days: 3, concentration_mg_per_ml: 4, notes: '0.1 mg/kg q12h (Short course D1).', category: 'Emergency' },
  { name: 'Diflucan', type: 'liquid', mg_per_kg: 12, doses_per_day: 1, duration_days: 7, concentration_mg_per_ml: 2, notes: 'Fluconazole. 6-12 mg/kg/dose.', category: 'Antifungal' },
  { name: 'Digibind', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 9.5, notes: 'Digoxin immune Fab. Dose based on serum level.', category: 'Emergency' },
  { name: 'Dormicum', type: 'liquid', mg_per_kg: 0.15, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 5, notes: 'Midazolam. 0.05-0.15 mg/kg IV.', category: 'Sedatives' },
  { name: 'Edemex', type: 'liquid', mg_per_kg: 0.05, doses_per_day: 1, duration_days: 7, concentration_mg_per_ml: 0.25, notes: 'Bumetanide. 0.005-0.1 mg/kg/dose.', category: 'Cardiac' },
  { name: 'Eltroxen', type: 'pill', mg_per_kg: 0.014, doses_per_day: 1, duration_days: 30, concentration_mg_per_ml: 0, notes: 'Levothyroxine. 10-14 mcg/kg/day.', category: 'Endocrine' },
  { name: 'EMLA', type: 'pill', mg_per_kg: 0, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 0, notes: 'Lidocaine/Prilocaine cream. Apply 1-2g.', category: 'Dermatological' },
  { name: 'Epoetin alpha', type: 'liquid', mg_per_kg: 400, doses_per_day: 1, duration_days: 30, concentration_mg_per_ml: 4000, notes: '200-400 iu/kg/dose 3-5x per week.', category: 'Miscellaneous' },
  { name: 'Erythrocin', type: 'liquid', mg_per_kg: 50, doses_per_day: 4, duration_days: 14, concentration_mg_per_ml: 40, notes: 'Erythromycin. 12.5 mg/kg/dose q6h.', category: 'Antibiotics' },
  { name: 'Famotidine', type: 'liquid', mg_per_kg: 0.5, doses_per_day: 1, duration_days: 7, concentration_mg_per_ml: 10, notes: '0.25-0.5 mg/kg/dose IV.', category: 'Gastrointestinal' },
  { name: 'Fentanyl', type: 'liquid', mg_per_kg: 0.004, doses_per_day: 6, duration_days: 1, concentration_mg_per_ml: 0.05, notes: '0.5-4 mcg/kg/dose IV slow push.', category: 'Sedatives' },
  { name: 'Fludrocortisone', type: 'pill', mg_per_kg: 0, doses_per_day: 1, duration_days: 30, concentration_mg_per_ml: 0, notes: '0.05 mg PO once daily.', category: 'Endocrine' },
  { name: 'Folic Acid', type: 'pill', mg_per_kg: 0.015, doses_per_day: 1, duration_days: 30, concentration_mg_per_ml: 0, notes: '15 mcg/kg/dose (max 50mcg/day).', category: 'Vitamins' },
  { name: 'Fortum', type: 'liquid', mg_per_kg: 90, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 25, notes: 'Ceftazidime. 30 mg/kg/dose q8-12h.', category: 'Antibiotics' },
  { name: 'Fungizone', type: 'liquid', mg_per_kg: 1, doses_per_day: 1, duration_days: 14, concentration_mg_per_ml: 5, notes: 'Amphotericin B. 0.25-1 mg/kg/day.', category: 'Antifungal' },
  { name: 'Garamycin', type: 'liquid', mg_per_kg: 4, doses_per_day: 1, duration_days: 7, concentration_mg_per_ml: 40, notes: 'Gentamicin. 4-5 mg/kg q24-48h.', category: 'Antibiotics' },
  { name: 'Gastrazole', type: 'pill', mg_per_kg: 1, doses_per_day: 1, duration_days: 14, concentration_mg_per_ml: 0, notes: 'Omeprazole. 0.5-1.5 mg/kg/day.', category: 'Gastrointestinal' },
  { name: 'Glypressin', type: 'liquid', mg_per_kg: 0.02, doses_per_day: 4, duration_days: 1, concentration_mg_per_ml: 0.2, notes: 'Terlipressin. 7-20 mcg/kg/dose IV bolus.', category: 'Emergency' },
  { name: 'Glucagon', type: 'liquid', mg_per_kg: 0.2, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 1, notes: '0.2 mg/kg/dose IV push/IM.', category: 'Emergency' },
  { name: 'Heparin', type: 'liquid', mg_per_kg: 75, doses_per_day: 1, duration_days: 7, concentration_mg_per_ml: 5000, notes: '75 units/kg load, then 28 units/kg/h.', category: 'Miscellaneous' },
  { name: 'Hyalase', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 150, notes: 'Hyaluronidase. 150 units SubQ around extravasation.', category: 'Emergency' },
  { name: 'Inderal', type: 'pill', mg_per_kg: 1, doses_per_day: 4, duration_days: 30, concentration_mg_per_ml: 0, notes: 'Propranolol. 0.25 mg/kg/dose PO q6h.', category: 'Cardiac' },
  { name: 'Actrapid', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 100, notes: 'Human Insulin. 0.01-0.1 unit/kg/h IVI.', category: 'Endocrine' },
  { name: 'Kapron', type: 'liquid', mg_per_kg: 10, doses_per_day: 3, duration_days: 3, concentration_mg_per_ml: 100, notes: 'Tranexamic acid. 10 mg/kg IV.', category: 'Emergency' },
  { name: 'Kayexalate', type: 'pill', mg_per_kg: 1000, doses_per_day: 4, duration_days: 1, concentration_mg_per_ml: 0, notes: 'Sodium Polystyrene Sulfonate. 1 g/kg/dose PO/PR.', category: 'Emergency' },
  { name: 'Konakion MM', type: 'liquid', mg_per_kg: 1, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 10, notes: 'Vit K1. 0.5-1 mg IM at birth.', category: 'Vitamins' },
  { name: 'L-Carnitine', type: 'liquid', mg_per_kg: 100, doses_per_day: 4, duration_days: 30, concentration_mg_per_ml: 300, notes: '10-100 mg/kg/day.', category: 'Vitamins' },
  { name: 'Lanoxin', type: 'liquid', mg_per_kg: 0.01, doses_per_day: 1, duration_days: 30, concentration_mg_per_ml: 0.05, notes: 'Digoxin. 4-5 mcg/kg/day maintenance.', category: 'Cardiac' },
  { name: 'Lanzor', type: 'pill', mg_per_kg: 1, doses_per_day: 1, duration_days: 14, concentration_mg_per_ml: 0, notes: 'Lanzoprazole. 0.73-1.66 mg/kg/day.', category: 'Gastrointestinal' },
  { name: 'Magnesium Sulphate', type: 'liquid', mg_per_kg: 50, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 100, notes: '25-50 mg/kg IV slow.', category: 'Emergency' },
  { name: 'Maxical-D', type: 'liquid', mg_per_kg: 50, doses_per_day: 2, duration_days: 30, concentration_mg_per_ml: 30, notes: 'Calcium Carbonate. 20-80 mg Ca/kg/day.', category: 'Vitamins' },
  { name: 'Maxipime', type: 'liquid', mg_per_kg: 100, doses_per_day: 2, duration_days: 7, concentration_mg_per_ml: 100, notes: 'Cefepime. 30-50 mg/kg/dose q12h.', category: 'Antibiotics' },
  { name: 'Meronem', type: 'liquid', mg_per_kg: 60, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 100, notes: 'Meropenem. 20 mg/kg/dose q8h.', category: 'Antibiotics' },
  { name: 'Miconaz Oral Gel', type: 'pill', mg_per_kg: 0, doses_per_day: 4, duration_days: 7, concentration_mg_per_ml: 0, notes: 'Miconazole. 1 ml 2-4 times daily.', category: 'Antifungal' },
  { name: 'Minophylline', type: 'liquid', mg_per_kg: 8, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 25, notes: 'Aminophylline. LD 8mg/kg, MD 1.5-3 mg/kg/dose.', category: 'Asthma' },
  { name: 'Milrinone', type: 'liquid', mg_per_kg: 0.075, doses_per_day: 1, duration_days: 3, concentration_mg_per_ml: 1, notes: 'LD 75 mcg/kg, MD 0.5-0.75 mcg/kg/min.', category: 'Cardiac' },
  { name: 'Morphine Sulphate', type: 'liquid', mg_per_kg: 0.2, doses_per_day: 6, duration_days: 3, concentration_mg_per_ml: 10, notes: '0.05-0.2 mg/kg/dose IV/IM/SubQ.', category: 'Sedatives' },
  { name: 'Motinorm', type: 'liquid', mg_per_kg: 0.25, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 1, notes: 'Domperidone. 0.25 mg/kg/dose up to 3x daily.', category: 'Gastrointestinal' },
  { name: 'Mucosolvan', type: 'liquid', mg_per_kg: 1.5, doses_per_day: 1, duration_days: 5, concentration_mg_per_ml: 7.5, notes: 'Ambroxol. 1.2-1.6 mg/kg/day.', category: 'Mucolytics' },
  { name: 'Mycostatin', type: 'liquid', mg_per_kg: 0, doses_per_day: 4, duration_days: 7, concentration_mg_per_ml: 100000, notes: 'Nystatin. 1-2 ml q6h after feeds.', category: 'Antifungal' },
  { name: 'Narcan', type: 'liquid', mg_per_kg: 0.1, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 0.4, notes: 'Naloxone. 0.1 mg/kg IV push/IM.', category: 'Emergency' },
  { name: 'Tobrin', type: 'liquid', mg_per_kg: 0, doses_per_day: 4, duration_days: 5, concentration_mg_per_ml: 3, notes: 'Tobramycin drops. 1-2 drops q4h.', category: 'Ophthalmic' },
  { name: 'Neostigmine', type: 'liquid', mg_per_kg: 0.15, doses_per_day: 4, duration_days: 7, concentration_mg_per_ml: 0.5, notes: '0.15 mg/kg IM/SubQ q6-8h.', category: 'Miscellaneous' },
  { name: 'Neupogen', type: 'liquid', mg_per_kg: 0.01, doses_per_day: 1, duration_days: 7, concentration_mg_per_ml: 0.3, notes: 'Filgrastim. 10 mcg/kg/dose SubQ q24h.', category: 'Miscellaneous' },
  { name: 'Nexium', type: 'pill', mg_per_kg: 0.5, doses_per_day: 1, duration_days: 7, concentration_mg_per_ml: 0, notes: 'Esomeprazole. 0.5 mg/kg/day.', category: 'Gastrointestinal' },
  { name: 'Noradrenaline', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 1, notes: '0.05-0.1 mcg/kg/min IVI.', category: 'Emergency' },
  { name: 'Orelox', type: 'liquid', mg_per_kg: 8, doses_per_day: 2, duration_days: 7, concentration_mg_per_ml: 8, notes: 'Cefpodoxime. 4 mg/kg/dose q12h.', category: 'Antibiotics' },
  { name: 'Phentolamine', type: 'liquid', mg_per_kg: 0.1, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 10, notes: 'Rogitine. 1-5 ml SubQ around extravasation.', category: 'Emergency' },
  { name: 'Polyvit', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 30, concentration_mg_per_ml: 0, notes: 'Multivitamin drops. 1 ml daily.', category: 'Vitamins' },
  { name: 'Potassium Chloride 15%', type: 'liquid', mg_per_kg: 1, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 150, notes: '0.5-1 mEq/kg (1 mEq = 0.5 ml).', category: 'Emergency' },
  { name: 'Potassium M syrup', type: 'liquid', mg_per_kg: 1, doses_per_day: 1, duration_days: 30, concentration_mg_per_ml: 33, notes: '0.5-1 mEq/kg/day divided with feeds.', category: 'Vitamins' },
  { name: 'Prostin-VR', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 0.5, notes: 'Prostaglandin E2. 0.05 mcg/kg/min IVI.', category: 'Emergency' },
  { name: 'Protam', type: 'liquid', mg_per_kg: 1, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 10, notes: 'Protamine Sulfate. 1 mg / 100 units heparin.', category: 'Emergency' },
  { name: 'Pulmicort', type: 'liquid', mg_per_kg: 0.5, doses_per_day: 2, duration_days: 5, concentration_mg_per_ml: 0.5, notes: 'Budesonide. 0.4-0.5 mg twice daily by nebulizer.', category: 'Asthma' },
  { name: 'Pulmozyme', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 30, concentration_mg_per_ml: 1, notes: 'Dornase alfa. 2500 units (2.5 mg) once daily.', category: 'Mucolytics' },
  { name: 'Pyridostigmine', type: 'pill', mg_per_kg: 1, doses_per_day: 4, duration_days: 30, concentration_mg_per_ml: 0, notes: 'Mestinon. Initially 1-1.5 mg/kg PO.', category: 'Miscellaneous' },
  { name: 'Rifampicin', type: 'liquid', mg_per_kg: 20, doses_per_day: 2, duration_days: 7, concentration_mg_per_ml: 20, notes: '5-10 mg/kg/dose IVI q12h. 10-20 mg/kg PO q24h.', category: 'Antibiotics' },
  { name: 'Sandostatin', type: 'liquid', mg_per_kg: 0.001, doses_per_day: 4, duration_days: 7, concentration_mg_per_ml: 0.1, notes: 'Octreotide. 1 mcg/kg/dose q6h SubQ/IV.', category: 'Gastrointestinal' },
  { name: 'Salbutamol', type: 'liquid', mg_per_kg: 0.5, doses_per_day: 4, duration_days: 5, concentration_mg_per_ml: 5, notes: 'Farcolin. 0.1-0.5 mg q2-6h via nebulizer.', category: 'Asthma' },
  { name: 'Simethicone', type: 'liquid', mg_per_kg: 0, doses_per_day: 6, duration_days: 7, concentration_mg_per_ml: 20, notes: '21 mg with or after each feed.', category: 'Gastrointestinal' },
  { name: 'SMOFlipids', type: 'liquid', mg_per_kg: 1000, doses_per_day: 1, duration_days: 7, concentration_mg_per_ml: 200, notes: 'Lipid Emulsion 20%. Start 0.5 g/kg/day.', category: 'Miscellaneous' },
  { name: 'Solu-Cortef', type: 'liquid', mg_per_kg: 1, doses_per_day: 2, duration_days: 12, concentration_mg_per_ml: 50, notes: 'Hydrocortisone. 0.5 mg/kg/dose IV q12h.', category: 'Emergency' },
  { name: 'Unasyn (750)', type: 'liquid', mg_per_kg: 150, doses_per_day: 2, duration_days: 7, concentration_mg_per_ml: 37.5, notes: 'Ampicillin/Sulbactam. 150 mg/kg/day IV.', category: 'Antibiotics' },
  { name: 'Ursogall', type: 'liquid', mg_per_kg: 30, doses_per_day: 2, duration_days: 30, concentration_mg_per_ml: 31.7, notes: 'Ursodeoxycholic acid. 10-15 mg/kg/dose PO q12h.', category: 'Gastrointestinal' },
  { name: 'Vancomycin (Ref)', type: 'liquid', mg_per_kg: 15, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 5, notes: '10-15 mg/kg/dose IVI over 1h.', category: 'Antibiotics' },
  { name: 'Valium', type: 'liquid', mg_per_kg: 0.3, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 5, notes: 'Diazepam. 0.1-0.3 mg/kg/dose slow IV.', category: 'Sedatives' },
  { name: 'Vfend', type: 'pill', mg_per_kg: 20, doses_per_day: 2, duration_days: 21, concentration_mg_per_ml: 0, notes: 'Voriconazole. 12-20 mg/kg/day divided q8-12h.', category: 'Antifungal' },
  { name: 'Viagra', type: 'pill', mg_per_kg: 2, doses_per_day: 4, duration_days: 30, concentration_mg_per_ml: 0, notes: 'Sildenafil. 0.5-2 mg/kg/dose PO q6-12h.', category: 'Cardiac' },
  { name: 'Vitalipid N', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 30, concentration_mg_per_ml: 0, notes: 'Fat-Soluble Vitamins. Part of TPN.', category: 'Vitamins' },
  { name: 'Zantac (Ref)', type: 'liquid', mg_per_kg: 2, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 25, notes: 'Ranitidine. 2 mg/kg/dose PO q8h.', category: 'Gastrointestinal' },
  { name: 'Zithromax (Ref)', type: 'liquid', mg_per_kg: 10, doses_per_day: 1, duration_days: 5, concentration_mg_per_ml: 40, notes: 'Azithromycin. 10 mg/kg/dose q24h.', category: 'Antibiotics' },
  
  // Nutritionals
  { name: 'Breast Milk', type: 'liquid', mg_per_kg: 0, doses_per_day: 8, duration_days: 365, concentration_mg_per_ml: 0, notes: 'Term: 68 kcal/100ml. Preterm: 67 kcal/100ml.', category: 'Nutritionals' },
  { name: 'Aptamil 1', type: 'liquid', mg_per_kg: 0, doses_per_day: 8, duration_days: 365, concentration_mg_per_ml: 0, notes: 'Infant Milk Formula with Iron. 67 kcal/100ml.', category: 'Nutritionals' },
  { name: 'Bebelac 1', type: 'liquid', mg_per_kg: 0, doses_per_day: 8, duration_days: 365, concentration_mg_per_ml: 0, notes: 'Infant Milk Formula. 67 kcal/100ml.', category: 'Nutritionals' },
  { name: 'Bebelac EC', type: 'liquid', mg_per_kg: 0, doses_per_day: 8, duration_days: 365, concentration_mg_per_ml: 0, notes: 'Infant Milk for Extra Care. 66 kcal/100ml.', category: 'Nutritionals' },
  { name: 'Bebelac FL', type: 'liquid', mg_per_kg: 0, doses_per_day: 8, duration_days: 365, concentration_mg_per_ml: 0, notes: 'Infant Milk Free of Lactose. 66 kcal/100ml.', category: 'Nutritionals' },
  { name: 'Bebelac premature', type: 'liquid', mg_per_kg: 0, doses_per_day: 8, duration_days: 365, concentration_mg_per_ml: 0, notes: 'Formula for LBW Infants. 80 kcal/100ml.', category: 'Nutritionals' },
  { name: 'Hero Baby 1', type: 'liquid', mg_per_kg: 0, doses_per_day: 8, duration_days: 365, concentration_mg_per_ml: 0, notes: 'Infant Formula from Birth. 66 kcal/100ml.', category: 'Nutritionals' },
  { name: 'Infatrini', type: 'liquid', mg_per_kg: 0, doses_per_day: 8, duration_days: 365, concentration_mg_per_ml: 0, notes: 'High Calorie Formula. 100 kcal/100ml.', category: 'Nutritionals' },
  { name: 'NAN 1', type: 'liquid', mg_per_kg: 0, doses_per_day: 8, duration_days: 365, concentration_mg_per_ml: 0, notes: 'Starter Infant Formula with Iron. 67 kcal/100ml.', category: 'Nutritionals' },
  { name: 'Neocate', type: 'liquid', mg_per_kg: 0, doses_per_day: 8, duration_days: 365, concentration_mg_per_ml: 0, notes: 'Hypoallergenic Formula. 71 kcal/100ml.', category: 'Nutritionals' },
  { name: 'Nestogen', type: 'liquid', mg_per_kg: 0, doses_per_day: 8, duration_days: 365, concentration_mg_per_ml: 0, notes: 'Starter Infant Formula with Iron. 67 kcal/100ml.', category: 'Nutritionals' },
  { name: 'Primavita 1', type: 'liquid', mg_per_kg: 0, doses_per_day: 8, duration_days: 365, concentration_mg_per_ml: 0, notes: 'Infant Milk Formula. 69 kcal/100ml.', category: 'Nutritionals' },
  { name: 'S-26 AR', type: 'liquid', mg_per_kg: 0, doses_per_day: 8, duration_days: 365, concentration_mg_per_ml: 0, notes: 'Milk-Based Lactose-Free. 67 kcal/100ml.', category: 'Nutritionals' },
  { name: 'S-26 Gold', type: 'liquid', mg_per_kg: 0, doses_per_day: 8, duration_days: 365, concentration_mg_per_ml: 0, notes: 'Infant Formula. 67 kcal/100ml.', category: 'Nutritionals' },
  { name: 'S-26 HA', type: 'liquid', mg_per_kg: 0, doses_per_day: 8, duration_days: 365, concentration_mg_per_ml: 0, notes: 'Hypo-antigenic Formula. 68 kcal/100ml.', category: 'Nutritionals' },
  { name: 'S-26 PDF GOLD', type: 'liquid', mg_per_kg: 0, doses_per_day: 8, duration_days: 365, concentration_mg_per_ml: 0, notes: 'Milk for Premature Infants. 73 kcal/100ml.', category: 'Nutritionals' },
  { name: 'Similac NeoSure', type: 'liquid', mg_per_kg: 0, doses_per_day: 8, duration_days: 365, concentration_mg_per_ml: 0, notes: 'Formula for Premature Infants. 74.4 kcal/100ml.', category: 'Nutritionals' },

  // Rest of original meds from server.ts (merged/re-added)
  { name: 'Adrenaline', type: 'liquid', mg_per_kg: 0.01, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 1, notes: '0.01 mg/kg per dose', category: 'Emergency' },
  { name: 'Atropine (Ref)', type: 'liquid', mg_per_kg: 0.02, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 0.1, notes: '0.02 mg/kg per dose', category: 'Emergency' },
  { name: 'Diazepam (Ref)', type: 'liquid', mg_per_kg: 0.5, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 5, notes: '0.2-0.5 mg/kg per dose', category: 'Emergency' },
  { name: 'Hydrocortisone', type: 'liquid', mg_per_kg: 4, doses_per_day: 4, duration_days: 1, concentration_mg_per_ml: 50, notes: '2-4 mg/kg per dose', category: 'Emergency' },
  { name: 'Lasix (Ref)', type: 'liquid', mg_per_kg: 1, doses_per_day: 2, duration_days: 1, concentration_mg_per_ml: 10, notes: 'Furosemide. 1 mg/kg per dose', category: 'Emergency' },
  { name: 'Epanutin (Ref)', type: 'liquid', mg_per_kg: 20, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 50, notes: '15-20 mg/kg loading', category: 'Anticonvulsants' },
  { name: 'Depakine', type: 'liquid', mg_per_kg: 40, doses_per_day: 3, duration_days: 30, concentration_mg_per_ml: 57.6, notes: 'Sodium valproate. 20-40 mg/kg/day', category: 'Anticonvulsants' },
  { name: 'Keppra', type: 'liquid', mg_per_kg: 60, doses_per_day: 2, duration_days: 30, concentration_mg_per_ml: 100, notes: 'Levetiracetam. 20-60 mg/kg/day', category: 'Anticonvulsants' },
  { name: 'Tegretol', type: 'liquid', mg_per_kg: 20, doses_per_day: 2, duration_days: 30, concentration_mg_per_ml: 20, notes: 'Carbamazepine. 10-20 mg/kg/day', category: 'Anticonvulsants' },
  { name: 'Lamictal', type: 'pill', mg_per_kg: 0, doses_per_day: 1, duration_days: 30, concentration_mg_per_ml: 0, notes: 'Lamotrigine. According to protocol', category: 'Anticonvulsants' },
  { name: 'Depakine syr', type: 'liquid', mg_per_kg: 0, doses_per_day: 3, duration_days: 30, concentration_mg_per_ml: 57.6, notes: 'Sodium valproate.', category: 'Anticonvulsants' },
  { name: 'Fucidin cream', type: 'pill', mg_per_kg: 0, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 0, notes: '3 times daily', category: 'Dermatological' },
  { name: 'Bepanthen', type: 'pill', mg_per_kg: 0, doses_per_day: 3, duration_days: 7, concentration_mg_per_ml: 0, notes: '2-3 times daily', category: 'Dermatological' },
  { name: 'Elocon cream', type: 'pill', mg_per_kg: 0, doses_per_day: 1, duration_days: 7, concentration_mg_per_ml: 0, notes: 'Once daily', category: 'Dermatological' },
  { name: 'Kenacomb', type: 'pill', mg_per_kg: 0, doses_per_day: 2, duration_days: 7, concentration_mg_per_ml: 0, notes: 'Twice daily', category: 'Dermatological' },
  { name: 'Vigamox', type: 'liquid', mg_per_kg: 0, doses_per_day: 3, duration_days: 5, concentration_mg_per_ml: 0, notes: 'Moxifloxacin. Drop every 8 hours', category: 'Ophthalmic' },
  { name: 'Refresh tears', type: 'liquid', mg_per_kg: 0, doses_per_day: 4, duration_days: 5, concentration_mg_per_ml: 0, notes: 'According to need', category: 'Ophthalmic' },
  { name: 'Otrivin pediatric', type: 'liquid', mg_per_kg: 0, doses_per_day: 3, duration_days: 5, concentration_mg_per_ml: 0, notes: 'Drop every 8 hours', category: 'ENT' },
  { name: 'Nasacort', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 30, concentration_mg_per_ml: 0, notes: 'According to age', category: 'ENT' },
  { name: 'Otocalm drops', type: 'liquid', mg_per_kg: 0, doses_per_day: 3, duration_days: 3, concentration_mg_per_ml: 0, notes: 'According to case', category: 'ENT' },
  { name: 'Tamiflu', type: 'liquid', mg_per_kg: 0, doses_per_day: 2, duration_days: 5, concentration_mg_per_ml: 6, notes: 'Oseltamivir. According to weight', category: 'Antiviral' },
  { name: 'Zentel', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 3, concentration_mg_per_ml: 20, notes: 'Albendazole. According to age', category: 'Antiparasitic' },
  { name: 'Vermox', type: 'liquid', mg_per_kg: 0, doses_per_day: 2, duration_days: 3, concentration_mg_per_ml: 20, notes: 'Mebendazole. According to age', category: 'Antiparasitic' },
  { name: 'Normal saline (100ml)', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 0, notes: 'According to case', category: 'Fluids' },
  { name: 'Dextrose 5% (100ml)', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 0, notes: 'According to case', category: 'Fluids' },
  { name: 'Ringer lactate (100ml)', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 0, notes: 'According to case', category: 'Fluids' },
  { name: 'Hepatitis B vaccine', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 0, notes: 'According to schedule', category: 'Vaccines' },
  { name: 'MMR vaccine', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 0, notes: 'According to schedule', category: 'Vaccines' },
  { name: 'Polio vaccine', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 0, notes: 'According to schedule', category: 'Vaccines' },
  { name: 'Pentavalent vaccine', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 1, concentration_mg_per_ml: 0, notes: 'According to schedule', category: 'Vaccines' },
  { name: 'Paracetamol IV (1g/100ml)', type: 'liquid', mg_per_kg: 15, doses_per_day: 4, duration_days: 1, concentration_mg_per_ml: 10, notes: '15 mg/kg per dose', category: 'Miscellaneous' },
  { name: 'Aspirin', type: 'pill', mg_per_kg: 5, doses_per_day: 1, duration_days: 30, concentration_mg_per_ml: 0, notes: '3-5 mg/kg/day', category: 'Miscellaneous' },
  { name: 'Zinc syrup', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 14, concentration_mg_per_ml: 10, notes: '10-20 mg / day', category: 'Miscellaneous' },
  { name: 'ORS', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 3, concentration_mg_per_ml: 0, notes: 'Oral Rehydration Salts.', category: 'Miscellaneous' },
  { name: 'Calcium syrup', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 30, concentration_mg_per_ml: 0, notes: 'According to age', category: 'Miscellaneous' },
  { name: 'Multivitamin drops', type: 'liquid', mg_per_kg: 0, doses_per_day: 1, duration_days: 30, concentration_mg_per_ml: 0, notes: 'According to age', category: 'Miscellaneous' },
  { name: 'Probiotics', type: 'pill', mg_per_kg: 0, doses_per_day: 1, duration_days: 7, concentration_mg_per_ml: 0, notes: 'According to type', category: 'Miscellaneous' },
  { name: 'Salbutamol syrup', type: 'liquid', mg_per_kg: 0.2, doses_per_day: 3, duration_days: 5, concentration_mg_per_ml: 0.4, notes: '0.1-0.2 mg/kg per dose', category: 'Miscellaneous' },
  { name: 'Prednisolone syr', type: 'liquid', mg_per_kg: 2, doses_per_day: 1, duration_days: 5, concentration_mg_per_ml: 1, notes: '1-2 mg/kg/day', category: 'Miscellaneous' },
  { name: 'Hypertonic saline nebules', type: 'liquid', mg_per_kg: 0, doses_per_day: 3, duration_days: 3, concentration_mg_per_ml: 3, notes: 'According to case', category: 'Miscellaneous' },
];
